api_platform:
    version: '0.0.0'
    title: 'List'
    description: 'Oliboy50 List API'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
